# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yysUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 452)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 441, 411))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_1.setGeometry(QtCore.QRect(30, 30, 115, 19))
        self.radioButton_1.setObjectName("radioButton_1")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(170, 30, 61, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(310, 30, 61, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 60, 115, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setGeometry(QtCore.QRect(170, 60, 115, 19))
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup.addButton(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_6.setGeometry(QtCore.QRect(310, 60, 115, 19))
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup.addButton(self.radioButton_6)
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_1.setGeometry(QtCore.QRect(30, 310, 121, 41))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 310, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 140, 401, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_1 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_1.setGeometry(QtCore.QRect(40, 30, 41, 22))
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 30, 41, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(240, 30, 41, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(330, 30, 41, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_7.setGeometry(QtCore.QRect(30, 90, 115, 19))
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup.addButton(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_8.setGeometry(QtCore.QRect(170, 90, 115, 19))
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup.addButton(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_9.setGeometry(QtCore.QRect(310, 90, 115, 19))
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup.addButton(self.radioButton_9)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 220, 401, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_times = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_times.setGeometry(QtCore.QRect(30, 30, 101, 31))
        self.lineEdit_times.setMaxLength(4)
        self.lineEdit_times.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_times.setObjectName("lineEdit_times")
        self.lineEdit_qqname = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_qqname.setGeometry(QtCore.QRect(260, 30, 101, 31))
        self.lineEdit_qqname.setMaxLength(10)
        self.lineEdit_qqname.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_qqname.setObjectName("lineEdit_qqname")
        self.comboBox_jienum = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_jienum.setGeometry(QtCore.QRect(230, 30, 41, 22))
        self.comboBox_jienum.setEditable(False)
        self.comboBox_jienum.setObjectName("comboBox_jienum")
        self.comboBox_jienum.addItem("")
        self.comboBox_jienum.addItem("")
        self.comboBox_jienum.addItem("")
        self.comboBox_jienum.addItem("")
        self.comboBox_xuenum = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_xuenum.setGeometry(QtCore.QRect(370, 30, 41, 22))
        self.comboBox_xuenum.setObjectName("comboBox_xuenum")
        self.comboBox_xuenum.addItem("")
        self.comboBox_xuenum.addItem("")
        self.comboBox_xuenum.addItem("")
        self.comboBox_xuenum.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(460, 10, 331, 431))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionsadf = QtWidgets.QAction(MainWindow)
        self.actionsadf.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/easyicon_net_512.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsadf.setIcon(icon)
        self.actionsadf.setObjectName("actionsadf")

        self.retranslateUi(MainWindow)
        self.buttonGroup.buttonClicked['int'].connect(MainWindow.setMod)
        self.pushButton_1.clicked.connect(MainWindow.start)
        self.pushButton_2.clicked.connect(MainWindow.stop)
        self.comboBox_jienum.currentTextChanged['QString'].connect(MainWindow.setjienum)
        self.comboBox_xuenum.currentTextChanged['QString'].connect(MainWindow.setxuenum)
        self.lineEdit_times.editingFinished.connect(MainWindow.settimes)
        self.lineEdit_qqname.editingFinished.connect(MainWindow.setqqname)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "痒痒鼠1.3"))
        self.groupBox.setTitle(_translate("MainWindow", "副本选择"))
        self.radioButton_1.setText(_translate("MainWindow", "设置窗口"))
        self.radioButton_2.setText(_translate("MainWindow", "结界"))
        self.radioButton_3.setText(_translate("MainWindow", "血月"))
        self.radioButton_4.setText(_translate("MainWindow", "组队探索"))
        self.radioButton_5.setText(_translate("MainWindow", "组队御魂觉醒"))
        self.radioButton_6.setText(_translate("MainWindow", "备用"))
        self.pushButton_1.setText(_translate("MainWindow", "启动"))
        self.pushButton_2.setText(_translate("MainWindow", "停止"))
        self.groupBox_2.setTitle(_translate("MainWindow", "窗口参数 指沙盒开启的窗口名"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_1.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "4"))
        self.radioButton_7.setText(_translate("MainWindow", "备用"))
        self.radioButton_8.setText(_translate("MainWindow", "备用"))
        self.radioButton_9.setText(_translate("MainWindow", "备用"))
        self.groupBox_3.setTitle(_translate("MainWindow", "副本参数"))
        self.comboBox_jienum.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_jienum.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_jienum.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_jienum.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_xuenum.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_xuenum.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_xuenum.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_xuenum.setItemText(3, _translate("MainWindow", "4"))
        self.actionsadf.setText(_translate("MainWindow", "sadf"))


